In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
## create a numpy array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2=np.array([1,2,3,4,5])  ## 1D array

arr2.reshape(1,5)  ## 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [11]:
## 2D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)  ## 2 row and 5 column


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)  ## convert 1D array to 2D array


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))  ## create an array of ones with 3 row and 4 column


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## identity matrix
np.eye(4)  ## create an identity matrix of size 4x4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr=np.array([[1,2,3],[4,5,6]])  ## attributes of numpy

print(arr)
print(arr.shape)  ## 2 row and 3 column 
print(arr.ndim)  ## number of dimensions
print(arr.size)  ## total number of elements in the array
print(arr.dtype)  ## data type of the elements in the array
print(arr.itemsize)  ## size of each element in bytes


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [22]:
## numpy vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print(arr1+arr2)  ## element-wise addition
print(arr1-arr2)  ## element-wise subtraction
print(arr1*arr2)  ## element-wise multiplication
print(arr1/arr2)  ## element-wise division


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [23]:
##universal functions in numpy
arr=np.array([1,2,3,4,5])
print(np.sqrt(arr))  ## square root of each element in the array    
print(np.exp(arr))  ## exponential of each element in the array
print(np.sin(arr))  ## sine of each element in the array
print(np.cos(arr))  ## cosine of each element in the array
print(np.tan(arr))  ## tangent of each element in the array


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [24]:
## array slicing and indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0])  ## first row
print(arr[1])  ## second row
print(arr[2])  ## third row


[1 2 3]
[4 5 6]
[7 8 9]


In [45]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(arr[0:2,2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


In [46]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [47]:
## modify the array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
## statistics concepts (normalization
## to have mean = 0 and standard deviation = 1)

data=np.array([1,2,3,4,5])

##calculate mean and standard deviation
mean=np.mean(data)
std=np.std(data)

## normalize the data
normalized_data=(data-mean)/std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
data=np.array([1,2,2,3,4,5,6,7,8,9,10])


# mean
mean=np.mean(data)
print("Mean:", mean)

## median
median=np.median(data)
print("Median:", median)

## standard deviation
std=np.std(data)
print("Standard Deviation:", std)

## variance
variance=np.var(data)
print("Variance:", variance)

Mean: 5.181818181818182
Median: 5.0
Standard Deviation: 2.9176011883420387
Variance: 8.512396694214877


In [60]:
## logical operations
arr=np.array([1,2,3,4,5])
arr[(arr>3) & (arr<5)] ## element-wise comparison    

array([4])